version: "3.3"
services:
    frontend: 
        restart: always
        container_name: 'nginx_fontend'
        depends_on: 
            - backend
        build: 
            context: ./App-Angular
            dockerfile: Dockerfile
        ports:
            - '4200:80'
        volumes:
            # inside /app in th container don't try to override this folder (node_modules)
            - /app/node_modules
            - ./App-Angular:/usr/src/app
    backend:
        depends_on: 
            - db
        restart: always
        build: 
            context: ./App-Python-Flask
            dockerfile: Dockerfile
        container_name: "python_flask_backend"
        ports:
            - '5001:5001'
        
#        environment:
#            - PGUSER=postgres
#            - PGHOST=postgres_db
#            - PGDATABASE=online-exam
#            - PGPASSWORD=root
#            - PGPORT=5432
    db:
        image: postgres
        ports:
            - '5432:5432'
        container_name: "postgres_db"
        environment:
            - POSTGRES_USER=postgres
#            - PGHOST=postgres_db
            - POSTGRES_DB=db-session
            - POSTGRES_PASSWORD=root
#            - PGPORT=5432
#    nginx:
#        build: 
#            dockerfile: Dockerfile
 #           context: ./nginx
  #      container_name: "nginx_lb"  
   #     ports: 
    #        - '3000:80'
     #   depends_on:
      #      - backend
       #     - frontend
